version: '3.1'
services:
  db:
    image: postgres:12-alpine
    container_name: 'Bank-API'
    ports:
      - '5432:5432'
    volumes:
      - ./pg:/docker-entrypoint-initdb.d/
    env_file: 
      - docker.env
